### ISSUE TITLE
Add leetcode problems links in html page 

### ISSUE THREAD

**Issue by draceel07** [draceel07/Leet_Code_#10]

**Comment by Himanshuxyzz** [comment]
> _No description provided._

i can do this ...

**Comment by draceel07** [comment]
> > _No description provided._
> 
> i can do this ...

yeah sure

**Comment by shashank1529** [comment]
@draceel07 please assign this task to me

**Comment by draceel07** [comment]
> @draceel07 please assign this task to me

well you can still add some more questions in any section "question should be related to the topic of that section" ,  i'll merge your pr 🙃
