### ISSUE TITLE
Adding dark mode functionality in html page

### ISSUE THREAD

**Issue by draceel07** [draceel07/Leet_Code_#17]

**Comment by AbhishekRP2002** [comment]
I want to work on this issue

**Comment by AadeshKabra** [comment]
Hi, I would like to work on this. Can you assign it to me?

**Comment by SatyajeetShinde** [comment]
I want to work on this issue, please assign this task to me.

**Comment by draceel07** [comment]
> I want to work on this issue

yeah sure go on and best of luck 😊
