### ISSUE TITLE
Can anyone add functionality for when any link is visited the colour should be changed for visited links

### ISSUE THREAD

**Issue by draceel07** [draceel07/Leet_Code_#18]

**Comment by MufaddalHakim** [comment]
I would like to work on this, please assign

**Comment by Luckshya1210** [comment]
Hey! can you assign this issue to me?

**Comment by draceel07** [comment]
> Hey! can you assign this issue to me?

yeah sure go on i'm assigning this to you best of luck 😄

**Comment by draceel07** [comment]
> I would like to work on this, please assign

well  you can check other issues i'll merge your pr 🙃

**Comment by Luckshya1210** [comment]
Ok! thanks

**Comment by Luckshya1210** [comment]
Raised a pull request. Pls review!
@draceel07

**Comment by Luckshya1210** [comment]
@draceel07 Pls add hacktoberfest and hacktoberfestaccepted label to my pr
