### ISSUE TITLE
Can someone implement feature in which even refreshing the page it does not revert the dark/light mode

### ISSUE THREAD

**Issue by draceel07** [draceel07/Leet_Code_#21]
Suppose if i toggle the dark mode but after refreshing the page it revert back to light mode again ....so i need a fix for it 😅

**Comment by jayeshs08** [comment]
hello @draceel07 kindly assign this to me. I would love to work on this issue!

**Comment by mohdimran25** [comment]
hey @draceel07 I am happy to help you on this issue. Assign it to me.

**Comment by draceel07** [comment]
> hey @draceel07 I am happy to help you on this issue. Assign it to me.

sure go on best of luck ✌️

**Comment by draceel07** [comment]
> hello @draceel07 kindly assign this to me. I would love to work on this issue!

you can contribute in other issues check them also ❤️
